# escape=`
FROM plugins/base:windows-ltsc2022-amd6

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Codacy" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-codacy.exe C:/bin/drone-codacy.exe
ENTRYPOINT [ "C:\\bin\\drone-codacy.exe" ]
